[package]
name = "cex_connector"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
base64 = "0.22.1"
rustls = "0.23.28"
sha1 = "0.10.6"
tokio = { version = "1.44.2", features = ["full"] }
webpki-roots = "1.0.0"
